name: phone2pc_client
description: Android client for Phone2PC input system.
publish_to: 'none'
version: 5.2.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.4.0
  flutter_local_notifications: ^17.0.0
  shared_preferences: ^2.2.0
  file_picker: ^8.0.0+1
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  open_file: ^3.3.2
  share_plus: ^7.2.2
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
